name: Lint files

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          # https://github.com/hadolint/hadolint/wiki/DL3018
          args: --ignore DL3018
