name: Lint Dockerfile
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Haskell Dockerfile Linter
      uses: docker://cdssnc/docker-lint-github-action
      with:
        # https://github.com/hadolint/hadolint/wiki/DL3018
        args: --ignore DL3018
